<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>$(NetTestVersion)</TargetFramework>
    <IsPackable>false</IsPackable>
    <OutputType>Exe</OutputType>
    <StartupObject>Hocon.Tests.Performance.Program</StartupObject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="NBench" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Hocon.Configuration\Hocon.Configuration.csproj" />
  </ItemGroup>

</Project>
